import {cookies} from "next/headers"; import {SignJWT,jwtVerify} from "jose"; import {createHash} from "node:crypto"; import {db} from "@/lib/db"; import {safeEqual} from "@/lib/core";
const name="equity_session", secret=()=>{const v=process.env.SESSION_SECRET;if(!v||v.length<32)throw new Error("SESSION_SECRET is missing");return new TextEncoder().encode(v)};
export const validCredentials=(u:string,p:string)=>!!process.env.ADMIN_USERNAME&&!!process.env.ADMIN_PASSWORD&&safeEqual(u,process.env.ADMIN_USERNAME!)&&safeEqual(p,process.env.ADMIN_PASSWORD!);
export async function session(){const token=(await cookies()).get(name)?.value;if(!token)return null;try{const {payload}=await jwtVerify(token,secret(),{algorithms:["HS256"]});return payload.role==="admin"&&typeof payload.username==="string"?{username:payload.username}:null}catch{return null}}
export async function signIn(username:string){const token=await new SignJWT({role:"admin",username}).setProtectedHeader({alg:"HS256"}).setIssuedAt().setExpirationTime("8h").sign(secret());(await cookies()).set(name,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:28800})}
export async function signOut(){(await cookies()).set(name,"",{httpOnly:true,path:"/",maxAge:0})}
export async function allowed(identity:string){const rows=await db()`INSERT INTO login_attempts(identity_hash,attempts) VALUES(${identity},1) ON CONFLICT(identity_hash) DO UPDATE SET attempts=CASE WHEN login_attempts.window_started_at<now()-interval '15 minutes' THEN 1 ELSE login_attempts.attempts+1 END,window_started_at=CASE WHEN login_attempts.window_started_at<now()-interval '15 minutes' THEN now() ELSE login_attempts.window_started_at END RETURNING attempts`;return Number((rows as any)[0]?.attempts??99)<=5}
export const identity=(ip:string,u:string)=>createHash("sha256").update(`${ip}:${u.toLowerCase()}`).digest("hex");
export async function clearAttempts(id:string){await db()`DELETE FROM login_attempts WHERE identity_hash=${id}`}
